theme: jekyll-theme-giellalt
title: Dictionary for Norwegian Bokmål ⇒ Kven
description: An electronic dictionary from Norwegian Bokmål to Kven

defaults:
  - scope: { path: "" }
    values:
      layout: default

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
